services:
  postgres:
    container_name: postgres-onion-blog
    image: postgres:15.0
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      -  postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - onion-blog
    restart: unless-stopped

  api:
    build: .
    container_name: blog-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - JWT_REFRESH_EXPIRATION_TIME=${JWT_REFRESH_EXPIRATION_TIME}
      - PROD_ADMIN_USERNAME=${PROD_ADMIN_USERNAME}
      - PROD_ADMIN_PASSWORD_HASH=${PROD_ADMIN_PASSWORD_HASH}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - postgres
    networks:
      - onion-blog
    restart: always

networks:
  onion-blog:
    driver: bridge

volumes:
  postgres_data:
    driver: local