spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  flyway:
    enabled: false

application:
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: ${JWT_EXPIRATION_TIME}
        refresh-token:
          expiration: ${JWT_REFRESH_EXPIRATION_TIME}

app:
  seed:
    admin:
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
